### ISSUE TITLE
Doesn't show the Form on front-end

### ISSUE THREAD

**Issue by fourroses666** [webber12/easyForm#1]
Looking for a Form Builder and found this one. 
I have installed it on Evo 1.4.0 RC3.
All seems to work (needs some restyling) but on the front-end I don't see the form.

(When giving an wrong formID I do get the message it doesn't exist.)

Installed from the Extras and my call is: 
`[!easyForm? &formid=`f2`!]`

Any idea what can be the issue?

Have added fields: name and email.
_Could it be the evo prefix?_

The database tables and fields exist;
evo_forms
evo_form_fields

**Comment by webber12** [comment]
May be there is no snippet eForm, installed in that version EvolutionCMS. Because esasyForm is only a wrapper for eForm snippet (it helps user to make formTpl and reportTpl for eForm without html-coding)

**Comment by fourroses666** [comment]
Thanks, I feel stupid. Didn't had eForm installed..
Just did a very basic form and works out of the box!

----

Are you still using it? It needs restyling and translation "placeholders" which I can help with.

Closing it

**Comment by fourroses666** [comment]
Did some restyling:

**module.easyForm.php**
you can remove the old styles
```
	<div class="tab-page" id="tabGeneral">	
		<div class="container container-body">
			<h2 class="tab">{$eF->zagol}</h2>
			<div class="action_info">{$eF->info}</div>
				<div class="table-responsive">
					{$eF->eBlock}
			 	</div>
				<form action="" method="post" id="delform" name="delform"> 
					<input type="hidden" name="delform1" value="" />
				</form>
				<form action="" method="post" id="delpole" name="delpole"> 
					<input type="hidden" name="delpole1" value="" />
				</form>
			</div>
		</div>
	</div>
```

**/config.php**
Add
```<table class="fl grid" cellspacing="1" cellpadding="1">```
and
```		<td><a href="[+moduleurl+]&fid=[+id+]&action=pole" class="btn btn-success">Lijst met velden</a></td>
		<td><a href="[+moduleurl+]&fid=[+id+]&action=edit" class="btn btn-success">Aanpassen</a></td>
		<td><a onclick="document.delform.delform1.value=[+id+];document.delform.submit();" style="cursor:pointer; color:#fff;" class="btn btn-success">Verwijderen</a></td>
```


All buttons:  class="btn btn-success"


<img width="1110" alt="easy" src="https://user-images.githubusercontent.com/523389/35221652-3921caee-ff7b-11e7-84ee-851e70f5eb4c.png">
